Update rsync-backup

diff --git a/rsync-backup b/rsync-backup
--- a/rsync-backup
+++ b/rsync-backup
@@ -5,7 +5,8 @@
 # Author: Eelke Smit
 # Email: mail [at] sjemm {dot} net
 # Please use/share/comment/reference
-# Date: 18-07-2017
+# Date: 23-08-2017
+# Requirements: fonts-symbola
 
 # Usage: run this script with arguments
 # Example: ./rsync-backup /home/music /backup/
@@ -17,94 +18,90 @@
 USER=UsertoNotify
 
 # Create a VAR of the rsync output to be used in the notification message
-OUTPUT=$(rsync -av --delete $1 $2)
+OUTPUT=$(rsync -a --delete $1 $2)
 
 case $? in
   0)
-    echo "Backup via Rsync Success" | systemd-cat -t rsync -p info
-    notify-matrix "Monitor notification: Backup via Rsync Success
-Back-upped: $1
-
-Here is the output:
-$OUTPUT"
+    echo "Backup of $1 Success" | systemd-cat -t rsync -p info
+    notify-matrix "✅ Backup of $1 Success"
     ;;
   1)
-    echo "Syntax or usage error" | systemd-cat -t rsync -p info
-    notify-matrix "Monitor notification: Hey $USER - Syntax or usage error"
+    echo "Backup of $1 Failed - Syntax or usage error" | systemd-cat -t rsync -p info
+    notify-matrix "⛔ $USER: Backup of $1 Failed"
     ;;
   2)
-    echo "Protocol incompatibility" | systemd-cat -t rsync -p info
-    notify-matrix "Monitor notification: Hey $USER -  Protocol incompatibility"
+    echo "Backup of $1 Failed - Protocol incompatibility" | systemd-cat -t rsync -p info
+    notify-matrix "⛔ $USER: Backup of $1 Failed"
     ;;
   3)
-    echo "Errors selecting input/output files, dirs" | systemd-cat -t rsync -p info
-    notify-matrix "Monitor notification: Hey $USER -  Errors selecting input/output files, dirs"
+    echo "Backup of $1 Failed - Errors selecting input/output files, dirs" | systemd-cat -t rsync -p info
+    notify-matrix "⛔ $USER: Backup of $1 Failed"
     ;;
   4)
-    echo "Requested action not supported: an attempt was made to manipulate 64-bit files on a platform that cannot support them; or an option was specified that is supported by the client and not by the server." | systemd-cat -t rsync -p info
-    notify-matrix "Monitor notification: Hey $USER -  Requested action not supported: an attempt was made to manipulate 64-bit files on a platform that cannot support them; or an option was specified that is supported by the client and not by the server."
+    echo "Backup of $1 Failed - Requested action not supported: an attempt was made to manipulate 64-bit files on a platform that cannot support them; or an option was specified that is supported by the client and not by the server." | systemd-cat -t rsync -p info
+    notify-matrix "⛔ $USER: Backup of $1 Failed"
     ;;
   5)
-    echo "Error starting client-server protocol" | systemd-cat -t rsync -p info
-    notify-matrix "Monitor notification: Hey $USER -  Error starting client-server protocol"
+    echo "Backup of $1 Failed - Error starting client-server protocol" | systemd-cat -t rsync -p info
+    notify-matrix "⛔ $USER: Backup of $1 Failed"
     ;;
   6)
-    echo "Daemon unable to append to log-file" | systemd-cat -t rsync -p info
-    notify-matrix "Monitor notification: Hey $USER -  Daemon unable to append to log-file"
+    echo "Backup of $1 Failed - Daemon unable to append to log-file" | systemd-cat -t rsync -p info
+    notify-matrix "⛔ $USER: Backup of $1 Failed"
     ;;
   10)
-    echo "Error in socket I/O" | systemd-cat -t rsync -p info
-    notify-matrix "Monitor notification: Hey $USER -  Error in socket I/O"
+    echo "Backup of $1 Failed - Error in socket I/O" | systemd-cat -t rsync -p info
+    notify-matrix "⛔ $USER: Backup of $1 Failed"
     ;;
   11)
-    echo "Error in file I/O" | systemd-cat -t rsync -p info
-    notify-matrix "Monitor notification: Hey $USER -  Error in file I/O"
+    echo "Backup of $1 Failed - Error in file I/O" | systemd-cat -t rsync -p info
+    notify-matrix "⛔ $USER: Backup of $1 Failed"
     ;;
   12)
-    echo "Error in rsync protocol data stream" | systemd-cat -t rsync -p info
-    notify-matrix "Monitor notification: Hey $USER -  Error in rsync protocol data stream"
+    echo "Backup of $1 Failed - Error in rsync protocol data stream" | systemd-cat -t rsync -p info
+    notify-matrix "⛔ $USER: Backup of $1 Failed"
     ;;
   13)
-    echo "Errors with program diagnostics" | systemd-cat -t rsync -p info
-    notify-matrix "Monitor notification: Hey $USER -  Errors with program diagnostics"
+    echo "Backup of $1 Failed - Errors with program diagnostics" | systemd-cat -t rsync -p info
+    notify-matrix "⛔ $USER: Backup of $1 Failed"
     ;;
   14)
-    echo "Error in IPC code" | systemd-cat -t rsync -p info
-    notify-matrix "Monitor notification: Hey $USER -  Error in IPC code"
+    echo "Backup of $1 Failed - Error in IPC code" | systemd-cat -t rsync -p info
+    notify-matrix "⛔ $USER: Backup of $1 Failed"
     ;;
   20)
-    echo "Received SIGUSR1 or SIGINT" | systemd-cat -t rsync -p info
-    notify-matrix "Monitor notification: Hey $USER -  Received SIGUSR1 or SIGINT"
+    echo "Backup of $1 Failed - Received SIGUSR1 or SIGINT" | systemd-cat -t rsync -p info
+    notify-matrix "⛔ $USER: Backup of $1 Failed"
     ;;
   21)
-    echo "Some error returned by waitpid()" | systemd-cat -t rsync -p info
-    notify-matrix "Monitor notification: Hey $USER -  Some error returned by waitpid()"
+    echo "Backup of $1 Failed - Some error returned by waitpid()" | systemd-cat -t rsync -p info
+    notify-matrix "⛔ $USER: Backup of $1 Failed"
     ;;
   22)
-    echo "Error allocating core memory buffers" | systemd-cat -t rsync -p info
-    notify-matrix "Monitor notification: Hey $USER -  Error allocating core memory buffers"
+    echo "Backup of $1 Failed - Error allocating core memory buffers" | systemd-cat -t rsync -p info
+    notify-matrix "⛔ $USER: Backup of $1 Failed"
     ;;
   23)
-    echo "Partial transfer due to error" | systemd-cat -t rsync -p info
-    notify-matrix "Monitor notification: Hey $USER -  Partial transfer due to error"
+    echo "Backup of $1 Failed - Partial transfer due to error" | systemd-cat -t rsync -p info
+    notify-matrix "⛔ $USER: Backup of $1 Failed"
     ;;
   24)
-    echo "Partial transfer due to vanished source files" | systemd-cat -t rsync -p info
-    notify-matrix "Monitor notification: Hey $USER -  Partial transfer due to vanished source files"
+    echo "Backup of $1 Failed - Partial transfer due to vanished source files" | systemd-cat -t rsync -p info
+    notify-matrix "⛔ $USER: Backup of $1 Failed"
     ;;
   25)
-    echo "The --max-delete limit stopped deletions" | systemd-cat -t rsync -p info
-    notify-matrix "Monitor notification: Hey $USER -  The --max-delete limit stopped deletions"
+    echo "Backup of $1 Failed - The --max-delete limit stopped deletions" | systemd-cat -t rsync -p info
+    notify-matrix "⛔ $USER: Backup of $1 Failed"
     ;;
   30)
-    echo "Timeout in data send/receive" | systemd-cat -t rsync -p info
-    notify-matrix "Monitor notification: Hey $USER -  Timeout in data send/receive"
+    echo "Backup of $1 Failed - Timeout in data send/receive" | systemd-cat -t rsync -p info
+    notify-matrix "⛔ $USER: Backup of $1 Failed"
     ;;
   35)
-    echo "Timeout waiting for daemon connection" | systemd-cat -t rsync -p info
-    notify-matrix "Monitor notification: Hey $USER -  Timeout waiting for daemon connection"
+    echo "Backup of $1 Failed - Timeout waiting for daemon connection" | systemd-cat -t rsync -p info
+    notify-matrix "⛔ $USER: Backup of $1 Failed"
     ;;
   *)
-    echo "Unknown return code $? from rsync" | systemd-cat -t rsync -p info
-    notify-matrix "Monitor notification: Hey $USER -  Unknown return code $? from rsync"
+    echo "Backup of $1 Failed - Unknown return code $? from rsync" | systemd-cat -t rsync -p info
+    notify-matrix "⛔ $USER: Backup of $1 Failed"
 esac
